#!/usr/bin/env bash
if [[ -z "$1" ]]; then
    echo "Usage: ./setup <foundation>"
    echo ""
    echo "Example usage:"
    echo "  ./setup bionic"
    exit 1
fi

FOUNDATION=$1
export DCMD_BASE="totalorder/dcmd-${FOUNDATION}:latest"
export DCMD_IMAGE="totalorder/dcmd-example-${FOUNDATION}:latest"
./build && bash -c "$(docker run --rm -i "${DCMD_IMAGE}" meta install-instructions)"
echo "Created executable ./exa"
